#!/bin/sh

2>/dev/null killall -9 wpa_supplicant

wpa_supplicant -B -iwlan0 -Dwext -c /etc/wpa_supplicant.conf

SSID=\"TP\"
PSK=\"acurarsx\"

wpa_cli -iwlan0 add_network
wpa_cli -iwlan0 set_network 0 ssid $SSID
wpa_cli -iwlan0 set_network 0 key_mgmt WPA-PSK
wpa_cli -iwlan0 set_network 0 psk $PSK

wpa_cli -iwlan0 set_network 0 scan_ssid 1
wpa_cli -iwlan0 enable_network 0
wpa_cli -iwlan0 select_network 0

ifconfig wlan0 192.168.1.88 netmask 255.255.255.0
route add default gw 192.168.1.1
echo nameserver 192.168.1.1 > /etc/resolv.conf
